name: Baby Taste Buds
favicon: null
layout_spectrum: 0.4445887899491936
typography_spectrum: 0.8028602066915482
title: Baby Taste Buds
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6240141703747213
  lightness: 0.08834448806010187
  saturation: 0.8180209014099091
  rhythmicContrast: 0.7161632666829973
purpose: []
